### ISSUE TITLE
Markdown rendering

### ISSUE THREAD

**Issue by jgroom33** [cidrblock/dld4e#14]
A [similar project](https://github.com/knsv/mermaid) renders in [Gitlab markdown](https://docs.gitlab.com/ee/user/markdown.html#mermaid)

This project should target the same.

I assume the requirement would be to add a feature to gitlab.  Is there a gating capability to allow this as a gitlab integration?

**Comment by jgroom33** [comment]
[pointer](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/assets/javascripts/behaviors/markdown/render_mermaid.js) to the implementation in Gitlab

**Comment by luiscachog** [comment]
+1

**Comment by jneidel** [comment]
This is marked "closed as completed".

Was it actually implemented? If yes, how would I use it?

I tried:

```
```drawthe.net
```drawthenet
```

I could also not find a reference in gitlab or online.
