### ISSUE TITLE
drawthe.net installation

### ISSUE THREAD

**Issue by bitintheskud** [cidrblock/dld4e#4]
Hi guys, 

Is it easy to install your app on a standalone server ? I would like to install it on our network for our developers and use our internal git. Tried to install it on a nodejs image without success but since I know shit in angular/js, this failed. Do you have any insight to give me to help install it, I can not bear more visio sh**..
Cheers

**Comment by cidrblock** [comment]
It's all client side except for two thing. Try running a web server in the root of the repo that serves up index.html. you should be able to render diagrams. The saving and retrieving won't work. The online version is using lambda and dynamo but could easily be switched to Python, flask, node and couch. That microservice just need to store yaml, and return a key, or take a key and return yaml. On vacation for another week or so but will check in after.

**Comment by bitintheskud** [comment]
Thanks, I tried that :) 
It will be great to be able to install this app on a server, most company does not allow to use external service with sensitive information. 
Enjoy your vacation !
